### Haoyan Lin

### INSTRUCTOR CONTENT -- REMOVE THIS IN STUDENT VERSION
#### The goals/notes for this class are:

* This assignment just involves review the take-away concepts from the PCA and making sure student understand all of the components of a neural network (e.g. input layer, hidden layer, outpuer layer, neurons, activation functions, etc)
* Once you review the PCA content, you have project groups give a short update on their projects to the class. Any time that is left over becomes project work time.

# Day 20 In-Class: Intro to Artificial Neural Networks

<img src="http://www.bogotobogo.com/python/scikit-learn/images/NeuralNetwork1/NN-with-components-w11-etc.png" width=600px>

### Agenda:

1. Review pre-class assignment
2. Present project updates
3. Work on semester projects!

----
# 1. Review pre-class assignment

Below is the solution to the pre-class assignment, we're going to talk through this to make sure we all understand what's happening.

In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

# input data (hours of sleep, hours of study)
X = np.array([[3,5], [5,1], [10,2]])

# normalized X
X_norm = X / np.max(X)
print("X_norm =")
print(X_norm)

# output data (test score)
y = np.array([[75], [83], [93]])

# normalized y
y_norm = y/100
print("y_norm =")
print(y_norm)

# Neural Network properties
inputLayerSize = 2
outputLayerSize = 1
hiddenLayerSize = 3

# Define synapse weights
W1 = np.random.randn(inputLayerSize, hiddenLayerSize)
W2 = np.random.randn(hiddenLayerSize, outputLayerSize)

# Apply the first weights to inputs to get hidden layer activity
Z2 = np.dot(X_norm, W1)
print("Z2 =")
print(Z2)

# Define our activation function
def sigmoid(z):
    #Apply sigmoid activation function to scalar, vector, or matrix
    return 1/(1+np.exp(-z))

# Apply the activation function to our activity levels
a2 = sigmoid(Z2)
print("a2 =")
print(a2)

# Apply the second weights to the hidden layer
Z3 = np.dot(a2, W2)
print("Z3 =")
print(Z3)

# Apply the activation function to produce prediction for yHat
yHat = sigmoid(Z3)

# Compare yhat to known y_norm
print("--------------")
print("How did we do?")
print("y_norm:")
print(y_norm)
print("yHat:")
print(yHat)

X_norm =
[[0.3 0.5]
 [0.5 0.1]
 [1.  0.2]]
y_norm =
[[0.75]
 [0.83]
 [0.93]]
Z2 =
[[-1.02477694 -1.048178    0.3859301 ]
 [-0.43864726 -0.51883909  0.31402499]
 [-0.87729452 -1.03767817  0.62804998]]
a2 =
[[0.26409796 0.25957513 0.59530257]
 [0.39206335 0.37312373 0.57786741]
 [0.29373873 0.26159824 0.65204717]]
Z3 =
[[-0.24964257]
 [-0.21048732]
 [-0.27134351]]
--------------
How did we do?
y_norm:
[[0.75]
 [0.83]
 [0.93]]
yHat:
[[0.43791148]
 [0.4475716 ]
 [0.43257729]]


---
# 2. Present project updates

Each group will have **~2 minutes** to update the class on where they are at with their projects. Make sure to pay attention in case you have questions or suggestions. You might also get some inspiration from another group!

----
# 3. Work on semester projects

This is a chance to make some progress on your project with your group while the instructors are around to help. Make use of it!

Before you leave, answer the following questions:

1. Where are you at with your project?
    - What have you accomplished? I finished the part of finding and import data and draw a draft plot.
    - What do you still need to do? I still need to analyze my data and support statement.
2. What do you think your biggest obstacle will be in completing your assignment?
I cannot setting the label by using pyplot.
3. When is your group going to meet to continue working on or finish the project?
We will work on our own part first and meet for getting result and conclusion toghter.

1. 
1) I finished the part of finding and import data and draw a draft plot.
2)  I still need to analyze my data and support statement.
2. I cannot setting the label by using pyplot.
3. We will work on our own part first and meet for getting result and conclusion toghter.

-----
### Congratulations, you're done!

Submit this notebook to D2L so that your instructor knows where you're at with your project!

&#169; Copyright 2018,  Michigan State University Board of Trustees